Repository Deltares/fews-web-oc, pull requests merged in 2024-10, with the labels that each got.

#1019 Use fixed width for date time column in table
  src/components/table/TimeSeriesTable.vue
  src/lib/table/createTableHeaders.ts
  src/lib/table/types/TableHeaders.ts
Labels: rel: improvement

#1023 Show topology node with only a scadaPanelId
  src/views/TopologyDisplayView.vue
Labels: rel: ignore

#1024 Only pass startTime and endTime for processData endpoint
  src/stores/workflows.ts
Labels: rel: fix

#1026 Fix linter issue
  .github/workflows/npm-deploy.yml
Labels: rel: ignore

#1032 Update README.md
  docs/public/configuration/README.md
Labels: rel: ignore

#1033 Fix issue with image placement when maps show multiple Earths
  src/components/wms/AnimatedRasterLayer.vue
Labels: rel: fix

#1038 Fix: topology node acts as link for leaf nodes with only a url
  src/components/general/TreeMenuItem.vue
  src/views/TopologyDisplayView.vue
Labels: rel: fix

#1040 Fix regression in topology navigation
  src/views/TopologyDisplayView.vue
Labels: rel: ignore
