Repository Deltares/fews-web-oc, pull requests merged in 2024-06, with the labels that each got.

#911 TimeSeriesTable: Increased the selection list values to 200, 500, 1000, 2000
  src/components/table/TimeSeriesTable.vue
Labels: DWO

#855 documented apache HTTPD
  docs/public/deployments/README.md
Labels: rel: ignore

#940 Only allow double click if onlyGrids has been set or not set at all.
  package-lock.json
  package.json
  src/components/spatialdisplay/SpatialDisplay.vue
Labels: rel: improvement

#944 Update documentation regarding release management
  docs/public/architecture/README.md
Labels: rel: ignore

#950 Change path to terms-and-conditions
  src/components/dialog/SplashScreenDialog.vue
  src/components/dialog/TermsOfUseDialog.vue
Labels: rel: improvement
