Repository Deltares/fews-web-oc, pull requests merged in 2024-11, with the labels that each got.

#1044 Fix range not updating legend when layer capabilities has no styles
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/services/useWms/index.ts
Labels: rel: fix

#1052 Fix download for empty qualifierId array
  src/components/download/DataDownloadDisplayComponent.vue
Labels: rel: fix

#1058 Fix regression on layerName
  src/lib/topology/displayTabs.ts
Labels: rel: ignore

#1046 Fix width of date table column
  src/components/table/TimeSeriesTable.vue
  src/lib/table/createTableHeaders.ts
  src/lib/table/types/TableHeaders.ts
Labels: rel: improvement

#1069 Show workflow dialog after map coordinate or bbox selection
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/stores/workflows.ts
  src/views/TopologyDisplayView.vue
Labels: bug, rel: ignore

#1067 Make series only editable if an editRequest is present in the request
  src/components/timeseries/TimeSeriesComponent.vue
  src/lib/charts/types/ChartSeries.ts
  src/lib/table/createTableHeaders.ts
Labels: rel: fix

#1072 Update README.md
  docs/public/configuration/README.md
Labels: rel: ignore

#1075 Update README.md
  docs/public/configuration/README.md
Labels: rel: ignore

#1081 Set correct dev deploy branch
  .github/workflows/npm-dev-deploy.yml
Labels: rel: ignore

#1084 Develop dashboard
  src/lib/topology/displayTabs.ts
Labels: rel: ignore

#1089 Remove special SSD dashboard panel treatment
  src/components/general/DashboardDisplay.vue
Labels: rel: ignore

#1091 Update README.md
  docs/public/project/README.md
Labels: rel: ignore
