Repository Deltares/fews-web-oc, pull requests merged in 2024-09, with the labels that each got.

#964 Update README.md
  docs/public/project/README.md
Labels: rel: ignore

#985 Remove else attribute in top template
  src/components/table/TableCell.vue
Labels: rel: ignore

#987 Remove min zoom setting on map
  src/components/map/MapComponent.vue
Labels: rel: improvement

#965 Update README.md
  docs/public/configuration/README.md
Labels: rel: ignore

#974 Rotate vertical profile icon
  src/components/spatialdisplay/SpatialTimeSeriesDisplay.vue
Labels: rel: improvement

#997 Revert jsonforms packages
  package-lock.json
  package.json
Labels: rel: ignore

#989 Add location information
  package-lock.json
  package.json
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/spatialdisplay/SpatialTimeSeriesDisplay.vue
  src/components/timeseries/TimeSeriesComponent.vue
  src/components/wms/TooltipPanel.vue
  src/lib/display/DisplayConfig.ts
  src/lib/filters/index.ts
  src/services/useDisplayConfig/index.ts
  src/services/useLocationTooltip/index.ts
Labels: rel: new feature

#1004 Update rollup
  package-lock.json
Labels: rel: ignore

#1011 Fix report screen only taking up half width
  src/views/ReportsDisplayView.vue
Labels: rel: ignore

#1012 Exclude vuetify from optimizedDeps in vite config
  vite.config.ts
Labels: rel: ignore

#1014 Do not hide icon image for selected location
  src/components/wms/LocationsLayer.vue
Labels: rel: improvement

#1017 Remove tooltip from map
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/wms/TooltipPanel.vue
Labels: rel: ignore
