Repository Deltares/fews-web-oc, pull requests merged in 2024-12, with the labels that each got.

#1102 Do no show node url in app bar
  src/views/TopologyDisplayView.vue
Labels: rel: improvement

#1109 Update README.md
  docs/public/README.md
Labels: rel: ignore

#1116 Do not capitalize layer title
  src/components/wms/InformationPanel.vue
Labels: rel: improvement

#1118 Make locations icons opaque
  src/components/wms/LocationsLayer.vue
Labels: rel: improvement

#1078 Keep zoom level the same between layers with the same bounds
  src/components/map/MapComponent.vue
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/wms/AnimatedRasterLayer.vue
Labels: rel: improvement

#1094 Set time zero for running tasks
  src/components/general/DateTimeField.vue
  src/components/workflows/WorkflowsControl.vue
  src/lib/date/index.ts
  src/stores/workflows.ts
Labels: rel: new feature

#1054 Remove report id from report selection and add current subtitle
  src/views/ReportsDisplayView.vue
Labels: rel: improvement

#1122 Limit height of chart time series chart, limit width of vertical profile
  src/components/charts/ElevationChart.vue
  src/components/charts/TimeSeriesChart.vue
Labels: rel: improvement

#1127 Restore time series download
  src/components/timeseries/TimeSeriesDisplay.vue
Labels: rel: ignore

#1135 Suppress maplibre abort errors since they trigger on normal behaviour
  src/components/wms/AnimatedRasterLayer.vue
Labels: rel: ignore

#1139 Remove alerts instead of deactivating them
  src/components/ssd/SchematicStatusDisplay.vue
  src/components/workflows/WorkflowsControl.vue
  src/layouts/DefaultLayout.vue
  src/stores/alerts.ts
Labels: rel: ignore

#1140 Add available workflows store
  src/lib/workflows/coordinates.ts
  src/lib/workflows/fetch.ts
  src/lib/workflows/index.ts
  src/lib/workflows/types.ts
  src/main.ts
  src/stores/availableWorkflows.ts
Labels: rel: ignore

#1144 Remove unused variables
  src/components/spatialdisplay/SpatialDisplayComponent.vue
Labels: rel: ignore

#1146 Remove test allerts
  src/layouts/DefaultLayout.vue
Labels: rel: ignore

#1148 Fix zoom on mobile being disabled
  src/components/map/MapComponent.vue
Labels: rel: fix

#1097 Use animated streamlines by default if available
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/wms/InformationPanel.vue
  src/stores/userSettings.ts
Labels: rel: improvement
