Repository Deltares/fews-web-oc, pull requests merged in 2025-03, with the labels that each got.

#1232 Add missing topology ssdtimeseriesdisplay to the router
  src/router/index.ts
Labels: rel: fix

#1215 Add log display
  src/components/logdisplay/LogDisplay.vue
  src/components/logdisplay/LogDisplayComponent.vue
  src/components/logdisplay/LogItem.vue
  src/components/logdisplay/LogMessageItem.vue
  src/components/logdisplay/LogTable.vue
  src/components/logdisplay/NewLogMessageDialog.vue
  src/components/logdisplay/TaskRunItem.vue
  src/components/wms/InformationPanel.vue
  src/components/wms/panel/InformationPanel.vue
  src/lib/date/index.ts
  src/lib/log/index.ts
  src/lib/log/types.ts
  src/lib/log/utils.ts
  src/lib/taskruns/status.ts
  src/lib/taskruns/types.ts
  src/lib/topology/displayTabs.ts
  src/lib/topology/nodes.ts
  src/lib/utils/types.ts
  src/router/index.ts
  src/services/authentication/AuthenticationManager.ts
  src/services/useCurrentUser/index.ts
  src/services/useLogDisplay/index.ts
  src/services/useLogDisplayLogs/index.ts
  src/services/useNoteGroup/index.ts
  src/services/useTaskRuns/index.ts
  src/views/SystemMonitorDisplayView.vue
Labels: rel: new feature

#1237 Fix log display vue prop type warnings
  src/components/logdisplay/LogDisplayComponent.vue
  src/components/logdisplay/LogItem.vue
Labels: rel: ignore

#1240 Increase precision of coordinate selector to 5 decimals latitude and longitude
  src/components/workflows/WorkflowsControl.vue
  src/lib/workflows/coordinates.ts
Labels: rel: improvement

#1242 Fix regression where map controls where still visible when selecting a workflow bounding box
  src/components/spatialdisplay/SpatialDisplayComponent.vue
Labels: rel: fix

#1234 Fix chart sometimes not updating when selecting locations
  src/components/spatialdisplay/SpatialDisplay.vue
  src/router/index.ts
Labels: rel: fix

#1244 Move available workflows fetch to store initialization
  src/components/download/TimeSeriesFileDownloadComponent.vue
  src/components/map/MapComponent.vue
  src/lib/fews-properties/fewsProperties.ts
  src/lib/requests/transformRequest.ts
  src/main.ts
  src/services/authentication/AuthenticationManager.ts
  src/stores/availableWorkflows.ts
Labels: rel: ignore

#1251 Allow user to add new row to table without data
  src/components/table/TimeSeriesTable.vue
Labels: rel: fix

#1253 Allow 0 to be used as a new row value
  src/components/table/TimeSeriesTable.vue
Labels: rel: fix

#1257 Add support for beta features in release notes
  .github/release.yml
Labels: rel: ignore

#1235 Fix wms sometimes not creating a source
  src/components/wms/AnimatedRasterLayer.vue
  src/components/wms/AnimatedStreamlineRasterLayer.vue
Labels: rel: ignore

#1136 Refresh timeseries automatically every 30s
  src/components/charts/TimeSeriesChart.vue
  src/components/timeseries/TimeSeriesComponent.vue
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
  src/lib/charts/types/ChartConfig.ts
  src/services/useDisplayConfig/index.ts
  src/services/useSsdPi/index.ts
  src/services/useTimeSeries/index.ts
Labels: rel: improvement

#1015 Center selected location marker when location is point geometry
  src/components/wms/LocationsLayer.vue
Labels: rel: ignore

#1246 Move overlay below location layer
  src/components/wms/LocationsLayer.vue
  src/components/wms/OverlayLayer.vue
  src/lib/map/index.ts
  src/lib/map/locations.ts
  src/lib/map/utils.ts
Labels: rel: improvement

#1260 1.3.0-rc.0
  package-lock.json
  package.json
Labels: rel: ignore

#1264 Update README.md
  docs/public/configuration/README.md
Labels: rel: ignore
