Repository Deltares/fews-web-oc, pull requests merged in 2025-05, with the labels that each got.

#1343 Fix color consistency on graphs
  package-lock.json
  package.json
  src/components/tasks/TaskRunSummary.vue
  src/services/useDisplayConfig/index.ts
  src/stores/taskRunColors.ts
Labels: rel: improvement

#1351 Only continue date time slider when loading of wms has finished
  src/components/general/DateTimeSlider.vue
  src/components/spatialdisplay/SpatialDisplayComponent.vue
Labels: rel: improvement

#1358 Upgrade GitHub Actions to v4 for checkout and setup-node in workflows
  .github/workflows/github-pages.yml
  .github/workflows/npm-build.yml
  .github/workflows/release.yml
Labels: rel: ignore

#1361 Move taskRun color to chart icon
  src/components/tasks/TaskRunSummary.vue
Labels: enhancement

#1362 Fix time params for data download
  src/components/download/TimeSeriesFileDownloadComponent.vue
Labels: rel: fix

#1352 Use time series thinning for charts but not for tables
  .github/workflows/github-pages.yml
  package-lock.json
  package.json
  src/components/charts/TimeSeriesChart.vue
  src/components/table/TimeSeriesTable.vue
  src/components/timeseries/TimeSeriesComponent.vue
  src/lib/display/DisplayConfig.ts
  src/services/useTimeSeries/index.ts
Labels: rel: new feature, rel: improvement

#1359 Allow panning in time series charts
  src/components/charts/TimeSeriesChart.vue
  src/components/timeseries/TimeSeriesComponent.vue
Labels: rel: new feature

#1369 Fix line endings
  src/lib/display/DisplayConfig.ts
  src/lib/topology/displayTabs.ts
Labels: rel: ignore

#1356 Add warning icon with stroke so warning color is more readable
  src/components/thresholds/ThresholdsButton.vue
Labels: rel: improvement

#1354 1353 dwo 1078 editacknowledgedelete log messages
  src/components/logdisplay/DateSeparator.vue
  src/components/logdisplay/LogDisplayComponent.vue
  src/components/logdisplay/LogItem.vue
  src/components/logdisplay/LogMessageItem.vue
  src/components/logdisplay/LogTable.vue
  src/lib/date/index.ts
  src/lib/log/actions.ts
  src/lib/log/index.ts
  src/lib/log/utils.ts
  src/services/useCurrentUser/index.ts
Labels: enhancement, DWO
