Repository Deltares/fews-web-oc, pull requests merged in 2025-06, with the labels that each got.

#1387 Update pi requests to 1.15.1
  package-lock.json
  package.json
  src/views/TopologyDisplayView.vue
Labels: rel: ignore

#1376 Fix reactivity issues in colourscales
  src/components/spatialdisplay/SpatialDisplayComponent.vue
Labels: bug, rel: fix

#1389 Update README.md
  docs/public/project/README.md
Labels: rel: ignore

#1385 Add support for dissemination of log messages
  src/components/logdisplay/LogDisplayComponent.vue
  src/components/logdisplay/LogDisseminations.vue
  src/components/logdisplay/LogItem.vue
  src/components/logdisplay/LogMessageItem.vue
  src/components/logdisplay/LogTable.vue
  src/lib/log/types.ts
  src/lib/log/utils.ts
Labels: rel: new feature

#1398 Use data analysis display endpoint for config instead of static
  package-lock.json
  package.json
  src/components/his/HisDataSelection.vue
  src/components/his/HisDisplayComponent.vue
  src/services/useDataAnalysisDisplay/index.ts
Labels: rel: beta

#1399 Change data analysis display icons
  src/components/his/HisDisplayComponent.vue
  src/lib/topology/component.ts
Labels: rel: beta

#1391 Prevent double action requests from firing
  src/services/useDisplayConfig/index.ts
Labels: rel: ignore

#1402 Fix charts not loading on initial load
  src/services/useDisplayConfig/index.ts
Labels: rel: fix

#1370 1333 poc document browser
  src/assets/attributeNames.json
  src/assets/browserLayout.json
  src/components/products/ProductDetails.vue
  src/components/products/ProductsBrowserPanel.vue
  src/components/products/ProductsBrowserTable.vue
  src/components/products/ProductsBrowserView.vue
  src/components/products/ReactiveIframe.vue
  src/components/products/productTools.ts
  src/components/time-control/IntervalSelector.vue
  src/lib/TimeControl/interval.ts
  src/lib/products/documentDisplay.ts
  src/lib/topology/component.ts
  src/lib/topology/dashboard.ts
  src/lib/topology/displayTabs.ts
  src/lib/topology/nodes.ts
  src/router/index.ts
  src/services/useProducts/index.ts
  src/services/useProducts/types.ts
  src/views/DocumentDisplayView.vue
  src/views/ProductReportView.vue
  src/views/TopologyDisplayView.vue
  vite.config.ts
Labels: rel: beta

#1410 Refactor HTML content handling in ProductsBrowserView and ProductReportView
  src/components/products/ProductsBrowserView.vue
  src/views/ProductReportView.vue
Labels: rel: ignore

#1412 Update pi requests to 1.17.0
  package-lock.json
  package.json
  src/lib/table/tableData.ts
Labels: rel: ignore

#1416 Fix plotId switching to 0 index
  src/services/useDisplayConfig/index.ts
Labels: rel: fix

#1414 Enable dynamic html display in dashboards
  src/components/dashboard/DashboardItem.vue
  src/views/DynamicReportDisplayView.vue
Labels: rel: fix

#1403 Add correlation from correlation endpoint
  src/components/analysis/AnalysisAddButton.vue
  src/components/analysis/AnalysisCollection.vue
  src/components/analysis/AnalysisCollectionChart.vue
  src/components/analysis/AnalysisCollectionCharts.vue
  src/components/analysis/AnalysisCorrelationChart.vue
  src/components/analysis/AnalysisDataSelection.vue
  src/components/analysis/AnalysisDisplayComponent.vue
  src/components/analysis/AnalysisFunctions.vue
  src/components/analysis/AnalysisMap.vue
  src/components/analysis/AnalysisMenu.vue
  src/components/analysis/DataAnalysisDisplay.vue
  src/components/analysis/functions/AnalysisCorrelation.vue
  src/components/analysis/functions/AnalysisTimeResampling.vue
  src/components/general/GroupSelect.vue
  src/components/his/HisCollectionCharts.vue
  src/components/his/functions/HisCorrelation.vue
  src/lib/analysis/collection.ts
  src/lib/analysis/correlation.ts
  src/lib/analysis/functions.ts
  src/lib/analysis/index.ts
  src/lib/analysis/types.ts
  src/lib/topology/dashboard.ts
  src/router/index.ts
  src/services/useCorrelation/index.ts
  src/services/useCorrelationChartData/index.ts
  src/services/useFilterLocations/index.ts
  src/services/useTimeSeries/index.ts
Labels: rel: beta

#1434 When the user login expired try a silent sign in on app init or reload
  src/services/authentication/AuthenticationManager.ts
Labels: rel: improvement

#1451 Fix threshold summary being overlapped
  src/components/thresholds/ThresholdsPanel.vue
Labels: rel: fix

#1450 Redirect to login page on silent sign-in failure
  src/services/authentication/AuthenticationManager.ts
Labels: rel: fix

#1454 Edit and save archive products in Report view
  src/components/reports/EditReport.vue
  src/lib/products/documentDisplay.ts
  src/lib/products/requests.ts
  src/lib/products/types.ts
  src/views/ProductReportView.vue
Labels: rel: new feature

#1429 Product upload and Delete in browserview
  src/components/products/ProductsBrowserTable.vue
  src/components/products/ProductsBrowserView.vue
  src/components/products/ReactiveIframe.vue
  src/lib/products/documentDisplay.ts
  src/lib/products/requests.ts
  src/services/useProducts/index.ts
  src/views/DocumentDisplayView.vue
  src/views/ProductReportView.vue
Labels: rel: new feature

#1452 Add ability to add data to existing plot on secondary y axis
  src/components/analysis/AnalysisAddButton.vue
  src/components/analysis/AnalysisAddToButton.vue
  src/components/analysis/AnalysisAsyncChart.vue
  src/components/analysis/AnalysisCollectionCharts.vue
  src/components/analysis/AnalysisCorrelationChart.vue
  src/components/analysis/AnalysisDataSelection.vue
  src/components/analysis/AnalysisDisplayComponent.vue
  src/components/analysis/AnalysisFilterChart.vue
  src/components/analysis/AnalysisProductChart.vue
  src/components/analysis/AnalysisUnsupportedChart.vue
  src/components/analysis/functions/AnalysisTimeResampling.vue
  src/components/general/Autocomplete.vue
  src/lib/analysis/filter.ts
  src/lib/analysis/types.ts
  src/lib/analysis/utils.ts
Labels: rel: beta

#1426 Use data analysis display config period for new collections
  src/components/analysis/AnalysisCollection.vue
  src/components/analysis/AnalysisDisplayComponent.vue
  src/components/general/Autocomplete.vue
  src/components/products/ProductsBrowserView.vue
  src/lib/TimeControl/interval.ts
  src/lib/analysis/collection.ts
  src/lib/analysis/types.ts
  src/lib/date/index.ts
  src/stores/systemTime.ts
  src/views/ProductReportView.vue
Labels: rel: beta

#1468 Improve data analysis display UI
  src/components/analysis/AnalysisAttributesFilter.vue
  src/components/analysis/AnalysisChartCard.vue
  src/components/analysis/AnalysisChartEdit.vue
  src/components/analysis/AnalysisDataSelection.vue
  src/components/analysis/AnalysisDisplayComponent.vue
  src/components/analysis/AnalysisFilterChart.vue
  src/components/analysis/AnalysisLineStyleEdit.vue
  src/components/analysis/AnalysisSettings.vue
  src/components/analysis/functions/AnalysisCorrelation.vue
  src/components/analysis/functions/AnalysisTimeResampling.vue
  src/components/general/EditableTitle.vue
  src/components/general/GroupSelect.vue
  src/components/general/SelectCard.vue
  src/lib/analysis/filter.ts
  src/lib/charts/styles.ts
  src/lib/topology/locations.ts
  src/services/useFilterLocations/index.ts
Labels: rel: beta

#1460 Improvement filtering & search log messages
  src/components/logdisplay/LogDisplayComponent.vue
  src/lib/log/utils.ts
Labels: rel: improvement

#1472 Add required check to whatif template errors
  src/lib/whatif/utils.ts
Labels: rel: fix

#1438 Include PDF Adobe fragments for PDF iframe src
  src/components/products/ProductsBrowserView.vue
  src/lib/products/utils.ts
Labels: rel: ignore

#1457 Add email sending functionality to ProductReportView
  package-lock.json
  package.json
  src/views/ProductReportView.vue
Labels: rel: new feature

#1475 chore: update dependencies and remove unused VNumberInput imports
  package-lock.json
  package.json
  src/components/analysis/AnalysisChartEdit.vue
  src/components/analysis/AnalysisSettings.vue
  src/components/analysis/functions/AnalysisCorrelation.vue
  src/components/logdisplay/LogTable.vue
  vite.config.ts
Labels: rel: improvement

#1477 Small UI updates
  src/components/analysis/AnalysisSettings.vue
  src/components/general/ShadowFrame.vue
  src/components/tasksdisplay/WhatIfTimeZeroSelect.vue
Labels: rel: ignore

#1480 Fix analysis workflow results
  package-lock.json
  package.json
  src/components/analysis/AnalysisAsyncChart.vue
  src/components/analysis/AnalysisFilterChart.vue
  src/components/analysis/workflows/AnalysisWorkflow.vue
  src/lib/analysis/filter.ts
  src/lib/analysis/types.ts
  src/lib/topology/component.ts
Labels: rel: beta

#1482 Add period to action urls without start end time
  src/lib/display/utils.ts
Labels: rel: fix

#1488 Fix vertical profile tab freezing browser
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
Labels: rel: fix

#1487 Determine file extension for document download
  src/components/products/ProductsBrowserView.vue
Labels: rel: ignore

#1485 Fix small analysis display bugs
  src/components/analysis/AnalysisCollection.vue
  src/components/analysis/AnalysisDisplayComponent.vue
  src/components/analysis/AnalysisSettings.vue
Labels: rel: beta
