Repository Deltares/fews-web-oc, pull requests merged in 2025-04, with the labels that each got.

#1266 Do not hardcode queryparameters in the time series edit POST
  src/components/timeseries/TimeSeriesComponent.vue
  src/lib/timeseries/types/SeriesHeader.ts
  src/services/useTimeSeries/index.ts
Labels: rel: fix

#1272 Fix dashboard css sometimes lingering
  src/components/general/DashboardDisplay.vue
  src/services/useDynamicCss/index.ts
Labels: rel: beta

#1273 1.3.0
  package-lock.json
  package.json
Labels: rel: ignore

#1274 Run release workflow on published not on created
  .github/workflows/release.yml
Labels: rel: ignore

#1276 Use vue-maplibre for animated raster layer
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/wms/AnimatedRasterLayer.vue
Labels: rel: fix

#1238 Add running task menu
  src/components/general/DataTable.vue
  src/components/logdisplay/LogItem.vue
  src/components/logdisplay/TaskRunItem.vue
  src/components/tasks/BaseTaskFilterControl.vue
  src/components/tasks/PeriodFilterControl.vue
  src/components/tasks/TaskRunProgress.vue
  src/components/tasks/TaskRunSummary.vue
  src/components/tasks/TaskRunsControl.vue
  src/components/tasks/TaskRunsPanel.vue
  src/components/tasks/TaskStatusFilterControl.vue
  src/components/tasks/WorkflowFilterControl.vue
  src/components/tasksdisplay/WhatIfDisplay.vue
  src/layouts/DefaultLayout.vue
  src/lib/date/index.ts
  src/lib/period/convert.ts
  src/lib/period/index.ts
  src/lib/period/types.ts
  src/lib/taskruns/convert.ts
  src/lib/taskruns/index.ts
  src/lib/taskruns/status.ts
  src/lib/taskruns/types.ts
  src/services/useFocusAwareInterval/index.ts
  src/services/useTasksRuns/index.ts
  src/services/useTimeSeries/index.ts
  src/services/useTopologyThresholds/index.ts
  src/services/useWhatIfTemplate/index.ts
  src/stores/availableWhatIfTemplates.ts
  src/stores/availableWorkflows.ts
  src/views/TopologyDisplayView.vue
Labels: rel: new feature

#1001 Show error message on failed data download
  src/components/download/TimeSeriesFileDownloadComponent.vue
  src/lib/download/downloadFiles.ts
Labels: rel: improvement

#1281 Fix streamline layer not passing JWT tokens for its requests
  package-lock.json
  package.json
  src/components/wms/AnimatedStreamlineRasterLayer.vue
Labels: rel: fix

#1248 Add navigation for dashboard and use navigate for ssd's
  src/components/general/DashboardItem.vue
  src/components/ssd/SchematicStatusDisplay.vue
  src/components/timeseries/TimeSeriesWindowComponent.vue
  src/lib/topology/dashboard.ts
  src/router/index.ts
  src/views/SchematicStatusDisplayView.vue
  src/views/TopologyDisplayView.vue
Labels: rel: improvement

#1283 Fix reports not loading when JWT token is needed
  package-lock.json
  package.json
  src/components/general/ShadowFrame.vue
  src/lib/charts/styles.ts
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
  src/lib/download/downloadFiles.ts
  src/services/useReport/index.ts
  src/stores/workflows.ts
  src/views/ReportsDisplayView.vue
Labels: rel: fix

#1285 Update pi requests to 1.12.5
  package-lock.json
  package.json
Labels: rel: ignore

#1279 Fix startPanel being overwritten and tooltip not loading when no timeseries is enabled
  src/components/spatialdisplay/SpatialDisplay.vue
  src/components/spatialdisplay/SpatialTimeSeriesDisplay.vue
  src/components/timeseries/TimeSeriesWindowComponent.vue
Labels: rel: fix

#1293 Update README.md
  docs/public/configuration/README.md
Labels: rel: ignore

#1295 Add wave crest visualisation
  package-lock.json
  package.json
  src/assets/wave-crest.svg
  src/components/wms/AnimatedStreamlineRasterLayer.vue
  src/views/SpatialDisplayView.vue
Labels: rel: new feature

#1294 Add dashboard interaction
  package-lock.json
  package.json
  src/components/dashboard/DashboardDisplay.vue
  src/components/dashboard/DashboardGroup.vue
  src/components/dashboard/DashboardItem.vue
  src/components/spatialdisplay/SpatialDisplay.vue
  src/components/ssd/SchematicStatusDisplay.vue
  src/components/timeseries/TimeSeriesComponent.vue
  src/components/timeseries/TimeSeriesDisplay.vue
  src/lib/display/DisplayConfig.ts
  src/lib/router/index.ts
  src/lib/router/types.ts
  src/lib/topology/dashboard.ts
  src/lib/topology/dashboardActions.ts
  src/lib/topology/displayTabs.ts
  src/services/useDisplayConfig/index.ts
  src/services/useSsd/index.ts
  src/services/useSsdPi/index.ts
  src/views/DashboardView.vue
  src/views/ReportsDisplayView.vue
  src/views/SchematicStatusDisplayView.vue
  src/views/SpatialDisplayView.vue
  src/views/TopologyDisplayView.vue
Labels: rel: beta

#1288 Fix mobile check for ssd's and ssd side panel
  src/components/ssd/SchematicStatusDisplay.vue
  src/layouts/DefaultLayout.vue
Labels: rel: fix

#1296 Fix time sometimes being undefined causing wms layer to not update
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/services/useSelectedDate/index.ts
Labels: rel: fix

#1298 Only enable dashboard slider if there are dates
  src/components/dashboard/DashboardDisplay.vue
Labels: rel: fix

#1300 Fix location markers shadow
  src/components/wms/LocationsLayer.vue
  src/components/wms/locations/LocationsMarkers.vue
Labels: rel: fix

#1301 Reduce max chart height single chart case
  src/components/charts/TimeSeriesChart.vue
Labels: rel: fix

#1302 Fix css race condition same specificity legend text color
  src/components/wms/ColourBar.vue
Labels: rel: fix

#1303 Fix legend arrow location
  src/components/charts/ChartLegend.vue
Labels: rel: fix

#1297 Add style option to streamline layer
  src/components/wms/AnimatedStreamlineRasterLayer.vue
Labels: rel: fix

#1304 Remove artifacts between bars in bar charts
  src/lib/charts/styles.ts
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
Labels: rel: fix

#1311 Fix spurious "interpolation" of missing data with unreliable flag
  src/lib/charts/dataFromResources.ts
  src/lib/timeseries/types/SeriesData.ts
Labels: rel: fix

#1312 Make time series not deeply reactive
  src/services/useTimeSeries/index.ts
Labels: rel: ignore

#1307 Fix chart display not closing when switching to map without locations
  src/components/spatialdisplay/SpatialDisplay.vue
Labels: rel: fix

#1321 Update pi requests to 1.13.5
  package-lock.json
  package.json
Labels: rel: ignore

#1324 Update pi-requests to 1.13.6
  package-lock.json
  package.json
Labels: rel: ignore

#1319 Add ability to visualize task runs through the tasks menu
  src/components/charts/ChartLegend.vue
  src/components/charts/TimeSeriesChart.vue
  src/components/spatialdisplay/SpatialTimeSeriesDisplay.vue
  src/components/tasks/TaskRunProgress.vue
  src/components/tasks/TaskRunSummary.vue
  src/components/tasks/TaskRunsControl.vue
  src/components/tasks/TaskRunsPanel.vue
  src/components/tasks/TaskStatusFilterControl.vue
  src/components/timeseries/TimeSeriesComponent.vue
  src/components/timeseries/TimeSeriesDisplay.vue
  src/layouts/DefaultLayout.vue
  src/lib/charts/tags.ts
  src/lib/display/DisplayConfig.ts
  src/lib/taskruns/index.ts
  src/lib/taskruns/status.ts
  src/lib/taskruns/types.ts
  src/lib/taskruns/utils.ts
  src/services/useDisplayConfig/index.ts
  src/services/useSsdPi/index.ts
  src/services/useTasksRuns/index.ts
  src/stores/taskRuns.ts
  src/views/TopologyDisplayView.vue
Labels: rel: new feature

#1320 Add now line to indicate the current time
  src/components/charts/TimeSeriesChart.vue
  src/components/dashboard/DashboardDisplay.vue
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/timeseries/TimeSeriesComponent.vue
Labels: rel: new feature

#1325 Fix default selection of task runs tab
  src/components/tasks/TaskRunsControl.vue
Labels: rel: ignore

#1323 Show name and select first instead of dropdown when there is only 1 what if template
  src/assets/JsonFormsConfig.json
  src/components/tasksdisplay/WhatIfDisplay.vue
Labels: rel: improvement

#1317 Render more severe threshold locations on top
  src/lib/map/locations.ts
Labels: rel: improvement

#1310 Remove overlay chart legend min height to prevent empty lines
  src/components/charts/ChartLegend.vue
Labels: rel: improvement

#1322 Remove running tasks from system monitor
  src/components/systemmonitor/ImportStatusComponent.vue
  src/components/systemmonitor/RunningTasks.vue
  src/lib/table/types/TableHeaders.ts
  src/views/SystemMonitorDisplayView.vue
Labels: rel: improvement

#1306 Let map open chart when no sibling charts in dashboard group
  src/components/dashboard/DashboardDisplay.vue
  src/components/dashboard/DashboardGroup.vue
  src/components/dashboard/DashboardItem.vue
Labels: rel: beta

#1309 Fix dashboard interaction in case of different action ids in the same group
  src/components/dashboard/DashboardGroup.vue
  src/components/dashboard/DashboardItem.vue
  src/lib/topology/dashboardActions.ts
Labels: rel: beta

#1308 Fix all numberOfLines chart legend component setting
  src/components/charts/ChartLegend.vue
Labels: rel: fix

#1326 Add threshold widget
  src/components/general/ColumnItemIcon.vue
  src/components/general/ColumnMenu.vue
  src/components/general/LeafNodeButtons.vue
  src/components/general/TreeMenuItem.vue
  src/components/logdisplay/TaskRunItem.vue
  src/components/map/SyncMap.vue
  src/components/spatialdisplay/SpatialDisplay.vue
  src/components/tasks/TaskRunSummary.vue
  src/components/tasks/TaskRunsControl.vue
  src/components/tasks/TaskRunsPanel.vue
  src/components/thresholds/ThresholdSummary.vue
  src/components/thresholds/ThresholdSummaryChip.vue
  src/components/thresholds/ThresholdsButton.vue
  src/components/thresholds/ThresholdsControl.vue
  src/components/thresholds/ThresholdsField.vue
  src/components/thresholds/ThresholdsPanel.vue
  src/layouts/DefaultLayout.vue
  src/lib/charts/styles.ts
  src/lib/date/index.test.ts
  src/lib/date/index.ts
  src/lib/thresholds/index.ts
  src/lib/thresholds/types.ts
  src/services/useFocusAwareInterval/index.ts
  src/services/useTasksRuns/index.ts
  src/services/useTimeSeries/index.ts
  src/services/useTopologyThresholds/index.ts
  src/stores/locationNames.ts
  src/stores/parameters.ts
  src/stores/sidePanel.ts
  src/stores/warningLevels.ts
  src/views/TopologyDisplayView.vue
Labels: rel: new feature

#1329 Fix automatic not switching based on theme
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/stores/baseMaps.ts
Labels: rel: fix

#1332 Add thinsp between value and unit, grow value field when required
  src/components/thresholds/ThresholdsField.vue
Labels: rel: ignore

#1336 Add pointer-events-none class to prevent interaction on nested chip in thresholds
  src/App.vue
  src/components/thresholds/ThresholdsPanel.vue
Labels: rel: ignore
