Repository Deltares/fews-web-oc, pull requests merged in 2025-09, with the labels that each got.

#1570 Remove thresholds from horizontalcolorcode plot and correct order of timeseries
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
Labels: rel: fix

#1580 Move import status to sidebar
  src/components/systemmonitor/ImportStatusControl.vue
  src/components/systemmonitor/ImportStatusSummary.vue
  src/stores/sidePanel.ts
  src/views/TopologyDisplayView.vue
Labels: enhancement, DWO

#1585 Change visualisation for task that take longer than expected
  src/components/tasks/TaskRunProgress.vue
  src/components/tasks/TaskRunsPanel.vue
  src/lib/taskruns/status.ts
Labels: rel: improvement

#1600 Show select in user settings menu when setting has 4 options or more
  src/assets/DefaultUserSettings.json
  src/components/user-settings/UserSettings.vue
  src/components/user-settings/UserSettingsMenu.vue
Labels: rel: improvement

#1582 Fix period not always being set for timeseries requests
  src/lib/display/utils.ts
  src/lib/period/convert.ts
  src/lib/period/index.ts
Labels: rel: fix

#1575 Use threshold scaling and label placement from config
  package-lock.json
  package.json
  src/components/charts/TimeSeriesChart.vue
  src/lib/charts/defaultDomain.ts
  src/lib/charts/thresholds.ts
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
  src/lib/charts/types/ChartConfig.ts
  src/lib/charts/types/ChartSeries.ts
  src/lib/charts/types/ThresholdLine.ts
Labels: rel: new feature
