Repository Deltares/fews-web-oc, pull requests merged in 2025-02, with the labels that each got.

#1191 Fix user being undefined before doing request with bearer token
  src/main.ts
  src/services/authentication/AuthenticationManager.ts
Labels: rel: ignore

#1193 Fix topology display not rerouting to spatial display
  src/views/TopologyDisplayView.vue
Labels: rel: ignore

#1195 Selecting a map location fires two getAction requests
  src/components/spatialdisplay/SpatialDisplay.vue
Labels: rel: fix

#1205 Update dev dependencies
  package-lock.json
  package.json
Labels: rel: ignore

#1207 Fix ssd stencil's .hydrated being overwritten by class v-bind
  src/components/ssd/SsdComponent.vue
Labels: rel: ignore

#1200 Hide scrollbars on fullscreen dashboard
  src/components/general/DashboardDisplay.vue
Labels: rel: ignore

#1206 Fix wrong map object being used for locations layer and selected coordinates layer
  src/components/wms/LocationsLayer.vue
  src/components/wms/SelectedCoordinateLayer.vue
Labels: rel: ignore

#1210 Add reason to abort
  src/components/wms/AnimatedStreamlineRasterLayer.vue
Labels: rel: fix

#1212 Make locations searchable by name and ID
  package.json
  src/components/general/GlobalSearchComponent.vue
  src/components/general/HighlightMatch.vue
  src/components/wms/LocationsSearchControl.vue
  src/lib/search/index.ts
  src/lib/search/substring.test.ts
  src/lib/search/substring.ts
  src/lib/search/types.ts
  src/stores/globalSearch.ts
Labels: rel: new feature

#1218 Fix animated streamlines layer with zero-valued elevation bounds
  package-lock.json
  package.json
Labels: rel: fix

#1213 Do not round off values in chart mouseover tooltips
  package-lock.json
  package.json
  src/components/charts/ElevationChart.vue
  src/components/charts/TimeSeriesChart.vue
Labels: rel: improvement

#1208 Refactor topology navigation
  src/components/spatialdisplay/SpatialDisplay.vue
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/wms/LocationsSearchControl.vue
  src/views/SpatialDisplayView.vue
  src/views/TopologyDisplayView.vue
Labels: rel: fix

#1203 Fix chartdisplay being shown as if on mobile on too large screens
  src/components/spatialdisplay/SpatialDisplay.vue
Labels: rel: ignore

#1223 Update terradraw to v1.2.0
  package-lock.json
  package.json
  src/components/map/DrawBoundingBoxControl.vue
Labels: rel: improvement

#1226 Fix locationsLayer show reactivity
  src/components/spatialdisplay/SpatialDisplayComponent.vue
Labels: rel: ignore

#1229 Fix for filter prop can be undefined
  src/components/spatialdisplay/SpatialTimeSeriesDisplay.vue
  src/services/useDisplayConfig/index.ts
Labels: rel: fix
