Repository Deltares/fews-web-oc, pull requests merged in 2025-07, with the labels that each got.

#1506 Fix issues with time series period
  src/components/charts/TimeSeriesChart.vue
  src/components/spatialdisplay/SpatialTimeSeriesDisplay.vue
  src/components/timeseries/TimeSeriesComponent.vue
  src/components/timeseries/TimeSeriesDisplay.vue
  src/lib/TimeControl/interval.ts
  src/lib/date/index.ts
  src/lib/display/utils.ts
  src/services/useDisplayConfig/index.ts
Labels: rel: fix

#1512 Fix enumproperties response of whatifscenario's being incorrect
  package-lock.json
  package.json
  src/lib/whatif/utils.ts
Labels: rel: fix

#1514 Fix what if scenario results only showing one line for each task run
  src/components/charts/TimeSeriesChart.vue
  src/lib/charts/tags.ts
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
Labels: rel: fix

#1517 Fix parameter selection when clicking the checkbox itself for data analysis display
  src/components/general/SelectCard.vue
Labels: rel: beta

#1523 Fix github workflow test commands
  .github/workflows/npm-deploy.yml
  .github/workflows/npm-dev-deploy.yml
Labels: rel: ignore

#1489 Fix url with coordinates always closing
  src/components/spatialdisplay/SpatialDisplay.vue
  src/components/wms/AnimatedStreamlineRasterLayer.vue
  src/lib/topology/displayTabs.ts
  src/services/useFilterLocations/index.ts
  tests/e2e/topology/switchingMapNodes.spec.ts
Labels: rel: fix

#1496 Only show attributes filter if there are any filterable values
  src/components/analysis/AnalysisAttributesFilter.vue
Labels: rel: beta

#1499 Fix correlation charts not allowing for edits
  src/components/analysis/AnalysisCorrelationChart.vue
  src/components/analysis/AnalysisFilterChart.vue
  src/components/analysis/AnalysisPlotChart.vue
  src/components/analysis/functions/AnalysisCorrelation.vue
  src/lib/analysis/correlation.ts
  src/lib/analysis/types.ts
  src/lib/charts/styles.ts
  src/lib/charts/timeSeriesDisplayToChartConfig.ts
  src/services/useCorrelationChartData/index.ts
Labels: rel: beta

#1528 Add wms legends e2e test
  src/components/spatialdisplay/SpatialDisplayComponent.vue
  src/components/user-settings/UserSettings.vue
  src/components/user-settings/UserSettingsDialog.vue
  src/components/user-settings/UserSettingsMenu.vue
  src/components/wms/panel/ColourPanel.vue
  src/components/wms/panel/InformationPanel.vue
  tests/e2e/map/legend.spec.ts
  tests/e2e/topology/switchingMapNodes.spec.ts
Labels: rel: ignore

#1445 Allow scroll wheel zooming in charts while holding Shift
  package-lock.json
  package.json
  src/assets/DefaultUserSettings.json
  src/components/charts/TimeSeriesChart.vue
  src/stores/userSettings.ts
Labels: rel: new feature

#1531 Add tests for terms of service and splash screen dialog
  src/components/dialog/SplashScreenDialog.vue
  src/components/dialog/TermsOfUseDialog.vue
  tests/e2e/dialog/startupDialogs.spec.ts
Labels: rel: improvement

#1538 Remove webserver from e2e and let runner choose dev:e2e or preview:e2e
  developer.md
  package.json
  playwright-e2e.config.ts
Labels: rel: ignore

#1537 Fix autoselection of first topology Node and add tests for this
  src/stores/topologyNodes.ts
  src/views/TopologyDisplayView.vue
  tests/e2e/topology/DefaultSelection.spec.ts
Labels: rel: fix

#1543 Remove thresholdscontrol if disabled
  src/views/TopologyDisplayView.vue
  tests/e2e/topology/threshold-visibility.spec.ts
Labels: rel: fix

#1550 Small ui change in task overview (DWO-1140)
  src/components/tasks/TaskRunsControl.vue
  src/views/TopologyDisplayView.vue
Labels: DWO

#1553 Always show refresh for tasks
  src/components/tasks/TaskRunsPanel.vue
Labels: DWO, rel: fix

#1561 Add support for what if multiproperty
  package-lock.json
  package.json
  src/lib/whatif/utils.ts
Labels: rel: improvement
